{
  "hash": "80d16fd764f91427bd8a4fe96640e17f",
  "result": {
    "engine": "knitr",
    "markdown": "# Introduction to Posterior Simulation\n\n\n\n\n\n\n\n<!-- {{< include _python_setup.qmd >}} -->\n\n- All of Bayesian inference is based on the posterior distribution of parameters given sample data.\n- Therefore, the main computational task in a Bayesian analysis is computing, or approximating, the posterior distribution.\n\n::: {#exm-left-handed-normal-prior}\nSuppose we wish to estimate the proportion of Cal Poly students that are left-handed.\nSuppose we want to assume a Normal distribution prior for $\\theta$ with mean 0.15 and SD 0.08.\nAlso suppose that in a sample of 25 Cal Poly students 5 are left-handed.\nWe want to find the posterior distribution.\n\nNote: the Normal distribution prior assigns positive (but small) density outside of (0, 1). So we can either truncate the prior to 0 outside of (0, 1) or just rely on the fact that the likelihood will be 0 for $\\theta$ outside of (0, 1) to assign 0 posterior density outside (0, 1).\n:::\n\n1. Write an expression for the shape of the posterior density.\nIs this a recognizable probability distribution?\n\\\n\\\n\\\n\\\n\\\n\n1. Describe in full detail two methods for approximating the posterior distribution in this situation.\n\\\n\\\n\\\n\\\n\\\n\n- In most problems it is not possible to find the posterior distribution analytically, and therefore we must approximate it.\n- We have seen two approximation methods: grid approximation and simulation.\n\n::: {#exm-curse-of-dimensionality}\nSuppose you're interested in studying sleep hours of Cal Poly undergraduates.\nYou assume that within each of the six colleges sleep hours follow a Normal distribution with a mean and SD for the college.\nYou'll collect data on a random sample of students, record their college and sleep hours, and use it to perform a Bayesian analysis.\n:::\n\n1. How many parameters are there in this situation?\n\\\n\\\n\\\n\\\n\\\n\n1. Suppose you try a grid approximation.\nYou create a grid of 100 values over the possible range of values of each parameter.\nHow many rows would there be in the Bayes table?\n\\\n\\\n\\\n\\\n\\\n\n- Grid approximation suffers from the \"curse of dimensionality\" and is not computationally feasible in multi-parameter problems (and most interesting problems are multi-parameter).\n\n\n::: {#exm-describe-posterior-simulation}\nRecall that we have used simulation to approximate posterior distributions in a few situations: @exm-harry-potter-intro-posterior, @exm-data-singular-posterior, @exm-sleep-predict.\n:::\n\n1. Explain the general method for using simulation to approximate a posterior distribution given sample data.\nCareful: don't confuse posterior distributions with posterior predictive distributions.\n\\\n\\\n\\\n\\\n\\\n\n1. Explain why this method is typically not feasible in practice.\n(It might help to look at the simulation results from the examples referenced above.)\n\\\n\\\n\\\n\\\n\\\n\n\n\n- We have seen three ways to compute/approximate the posterior distribution\n    - *Math*. Only works in a few special cases (e.g., Beta-Binomial, Normal-Normal, conjugate prior situations).\n    - *Grid approximation*. Not feasible when there are more than just a few parameters.\n    - *Simulation*. By far the most common method, though we have only seen a very naive approach so far.\n- In principle, the posterior distribution $\\pi(\\theta|y)$ of parameters $\\theta$ given observed data $y$ can be approximated via simulation in the following way.\n    - Simulate a $\\theta$ value from the prior distribution ($\\theta$ could be a vector of parameters, e.g., $\\theta = (\\mu, \\sigma)$).\n    - Given the simulated $\\theta$, simulate hypothetical data $y$ from the corresponding conditional distribution of $y$ given $\\theta$ ($y$ could be a full sample, or the value of a sample statistic).\n    - Repeat many times and discard $(\\theta, y)$ pairs for which the simulated data $y$ is not equal to the observed data $y$\n    - Summarize the simulated $\\theta$ values for the remaining pairs (with $y$ equal to the observed data).\n- While this method works in principle, it is a very computationally inefficient way of approximating the posterior distribution, since in most cases (e.g., not-small sample, continuous variables) the probability of replicating the observed data $y$ is essentially 0.\n- Therefore, we need more efficient simulation algorithms for approximating posterior distributions.\n**Markov chain Monte Carlo (MCMC)** methods provide powerful and widely applicable algorithms for simulating from probability distributions, including complex and high-dimensional distributions.\nThese algorithms include Metropolis-Hastings, Gibbs sampling, Hamiltonian Monte Carlo (HMC), and No U-Turn sampling (NUTS), among others.\nWe will see later some of the ideas behind MCMC algorithms.\n- Regardless of which simulation algorithm we use to approximate the posterior distribution, there are 3 main inputs:\n    - Observed data $y$\n    - Model for the data, $f(y|\\theta)$ which depends on parameters $\\theta$.\n    (This model determines the likelihood function.)\n    - Prior distribution for parameters $\\pi(\\theta)$\n- We then employ some simulation algorithm to approximate the posterior distribution of $\\theta$ given the observed data $y$, $\\pi(\\theta|y)$, *without computing the posterior distribution.*\n\n\n\n## Introduction to `brms` {#sec-brms}\n\n- We will rely on the software package [`brms`](https://github.com/paul-buerkner/brms) (\"Bayesian Regression Models using Stan\") to carry out MCMC simulations.\n- `brms` is an interface for the MCMC software [Stan](https://mc-stan.org/).\n- Here are a few references for using `brms`\n    - [`brms`](https://paul-buerkner.github.io/brms/) site\n    - [*Bayesian Modeling using Stan*](https://bayesball.github.io/BRMS/) by Jim Albert (companion to Albert and Hu textbook)\n    - [*Doing Bayesian Data Analysis in brms and the tidyverse*](https://solomon.quarto.pub/dbda2/01.html) by A Solomon Kurz (companion to Kruschke's *Doing Bayesian Data Analysis*)\n    - [Parameterization of Response Distributions in `brms`](https://cran.r-project.org/web/packages/brms/vignettes/brms_families.html)\n    - [`brms` reference manual](https://cran.r-project.org/web/packages/brms/brms.pdf)\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(brms)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: Rcpp\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading 'brms' package (version 2.23.0). Useful instructions\ncan be found by typing help('brms'). A more detailed introduction\nto the package is available through vignette('brms_overview').\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'brms'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:tidybayes':\n\n    dstudent_t, pstudent_t, qstudent_t, rstudent_t\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:stats':\n\n    ar\n```\n\n\n:::\n:::\n\n\nWe will introduce some basic functionality of `brms` in a few examples we have encountered previously.\n\n### Example: inference for a population proportion\n\nRecall @exm-read-book-interval-posterior where we were interested in \n$\\theta$, the population proportion of American adults who have read a book in the last year.\nWe assumed a Normal prior distribution for $\\theta$ with prior mean 0.4 and prior standard deviation 0.1.\nIn a sample of 150 American adults, 113 have read a book in the past year.\n(The real sample was size 1502, but we looked at the smaller sample size first.)\n\nFirst we define the data.\nWe could just define the total number of successes and the sample size.\nHowever, data is most often input as individual values in un-summarized form (e.g., a csv file with one row for each observational unit), so this is what we'll do.\nWe'll create a vector with 113 1s (\"successes\") and 37 0s (\"failures\").\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata = data.frame(y = c(rep(1, 113), rep(0, 37)))\n\nggplot(data, aes(x = factor(y))) + geom_bar() + labs(x = \"y\")\n```\n\n::: {.cell-output-display}\n![](posterior-simulation_files/figure-pdf/unnamed-chunk-4-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nNote that since the data contains individual 1/0 values, the likelihood is determined by the *Bernoulli* distribution, a special case of Binomial with $n=1$.\nThat is, if $y_i$ denotes an individual value, then $y_i\\sim$ Bernoulli($\\theta$) = Binomial(1, $\\theta$).\n\nNext we fit the model to the data using the function `brm`.\nThe three inputs are:\n\n- Input 1: the data  \n`data = data`\n\n- Input 2: model for the data (likelihood)  \n`family = bernoulli(link = identity)`  \n`y ~ 1 # linear model with intercept only`\n\n- Input 3: prior distribution for parameters  \n`prior = prior(normal(0.4, 0.1), class = Intercept)`\n\n- Other arguments specify the details of the numerical algorithm; our specifications below will result in 10000 $\\theta$ values simulated from the posterior distribution.\n\n\nNote: as its name suggests `brms` is made for regression models (broadly). \nTherefore, we will usually specify the `formula` with regression model syntax.\nThis will be more natural when we actually get to regression models, but it's a little clunky for some of the very basic models we have seen so far.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <-\n  brm(\n    data = data,\n    family = bernoulli(link = identity),\n    formula = y ~ 1,\n    prior(normal(0.4, 0.1), class = Intercept),\n    iter = 11000,\n    warmup = 1000,\n    chains = 1,\n    refresh = 0\n  )\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCompiling Stan program...\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nStart sampling\n```\n\n\n:::\n:::\n\n\nHere is a brief summary of results.\nNotice that \"Estimate\" is the posterior mean, \"\"Est.Error\" is the posterior standard deviation, and \"l-95% CI, u-95% CI\" are the endpoints of a posterior 95% credible interval.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: bernoulli \n  Links: mu = identity \nFormula: y ~ 1 \n   Data: data (Number of observations: 150) \n  Draws: 1 chains, each with iter = 11000; warmup = 1000; thin = 1;\n         total post-warmup draws = 10000\n\nRegression Coefficients:\n          Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept     0.71      0.04     0.64     0.77 1.00     4009     5442\n\nDraws were sampled using sampling(NUTS). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n\n:::\n:::\n\n\n\nHere are some plots.\nThe plot on the left represents the posterior distribution of $\\theta$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(fit)\n```\n\n::: {.cell-output-display}\n![](posterior-simulation_files/figure-pdf/unnamed-chunk-7-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nThe `b_Intercept` row in the `posterior_summary` below contains the posterior mean (\"Estimate\"), SD (\"Est.Error\"), median (\"Q50\"), and endpoints of central 50%, 80%, and 98% credible intervals.\nCompare to the grid approximation in @exm-read-book-interval-posterior; the results are very similar.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nposterior_summary(fit, probs = c(0.01, 0.10, 0.25, 0.50, 0.75, 0.90, 0.99))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              Estimate  Est.Error         Q1         Q10         Q25\nb_Intercept   0.707897 0.03556536   0.620596   0.6612202   0.6848232\nIntercept     0.707897 0.03556536   0.620596   0.6612202   0.6848232\nlprior       -3.419621 1.08764709  -6.127092  -4.8261475  -4.1310129\nlp__        -88.410800 0.70711336 -91.295426 -89.2551486 -88.5580201\n                    Q50         Q75         Q90         Q99\nb_Intercept   0.7090404   0.7321042   0.7524144   0.7875755\nIntercept     0.7090404   0.7321042   0.7524144   0.7875755\nlprior       -3.3916527  -2.6725663  -2.0281518  -1.0494835\nlp__        -88.1351184 -87.9695356 -87.9313261 -87.9239804\n```\n\n\n:::\n:::\n\n\nThere are commands within `brms` for working with simulation output.\nBut using `spread_draws` from the `tidybayes` package, we can put the 10000 simulated values into a data frame.\nThen we can summarize the posterior distribution just like we summarize any data set.\n\nBelow we save simulated values of `theta` in the `posterior` data frame.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidybayes)\n\nposterior_df = fit |>\n  spread_draws(b_Intercept) |>\n  rename(theta = b_Intercept)\n\nposterior_df |> head(10) |> kbl() |> kable_styling()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}[t]{r|r|r|r}\n\\hline\n.chain & .iteration & .draw & theta\\\\\n\\hline\n1 & 1 & 1 & 0.7166199\\\\\n\\hline\n1 & 2 & 2 & 0.7324163\\\\\n\\hline\n1 & 3 & 3 & 0.6957477\\\\\n\\hline\n1 & 4 & 4 & 0.7426208\\\\\n\\hline\n1 & 5 & 5 & 0.7083129\\\\\n\\hline\n1 & 6 & 6 & 0.6874246\\\\\n\\hline\n1 & 7 & 7 & 0.6792586\\\\\n\\hline\n1 & 8 & 8 & 0.6398941\\\\\n\\hline\n1 & 9 & 9 & 0.6795586\\\\\n\\hline\n1 & 10 & 10 & 0.6714900\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n\n\n:::\n:::\n\n\nNow we can plot values of `theta` as usual, e.g., using `ggplot2`.\n\nHere is a histogram of the simulated $\\theta$ values, with the approximate posterior density overlaid.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nposterior_df |>\n  ggplot(aes(x = theta)) +\n  geom_histogram(\n    aes(y = after_stat(density)),\n    col = bayes_col[\"posterior\"],\n    fill = \"white\"\n  ) +\n  geom_density(linewidth = 1, col = bayes_col[\"posterior\"]) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](posterior-simulation_files/figure-pdf/unnamed-chunk-10-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\nHere is a plot of the approximate posterior cumulative distribution function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nposterior_df |>\n  ggplot(aes(x = theta)) +\n  stat_ecdf(col = bayes_col[\"posterior\"], linewidth = 1) +\n  labs(title = \"Posterior cdf of theta\", y = \"Cumulative probability\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](posterior-simulation_files/figure-pdf/unnamed-chunk-11-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nWe can use the simulated values to approximate posterior mean and SD as usual.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(posterior_df$theta)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.707897\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsd(posterior_df$theta)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.03556536\n```\n\n\n:::\n:::\n\n\n\nQuantiles of the posterior distribution of $\\theta$ are endpoints of credible intervals.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquantile(posterior_df$theta, c(0.01, 0.10, 0.25, 0.75, 0.90, 0.99))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       1%       10%       25%       75%       90%       99% \n0.6205960 0.6612202 0.6848232 0.7321042 0.7524144 0.7875755 \n```\n\n\n:::\n:::\n\n\nWe can approximate the posterior probability that $\\theta$ is greater than 0.7 as usual.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(posterior_df$theta > 0.7) / length(posterior_df$theta)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6042\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(posterior)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThis is posterior version 1.6.1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'posterior'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:stats':\n\n    mad, sd, var\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:base':\n\n    %in%, match\n```\n\n\n:::\n:::\n\n\nThe function `as_draws_df` from the `posterior` packages also puts the `brms` output into a data frame (similar to `tidybayes::spread_draws`).\n\n\n::: {.cell}\n\n```{.r .cell-code}\npost_draws <- as_draws_df(fit)\n\nhead(post_draws)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A draws_df: 6 iterations, 1 chains, and 4 variables\n  b_Intercept Intercept lprior lp__\n1        0.72      0.72   -3.6  -88\n2        0.73      0.73   -4.1  -88\n3        0.70      0.70   -3.0  -88\n4        0.74      0.74   -4.5  -88\n5        0.71      0.71   -3.4  -88\n6        0.69      0.69   -2.7  -88\n# ... hidden reserved variables {'.chain', '.iteration', '.draw'}\n```\n\n\n:::\n:::\n\n\nThe `bayesplot` package has lots of nice built in plots.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(bayesplot)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThis is bayesplot version 1.14.0\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n- Online documentation and vignettes at mc-stan.org/bayesplot\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n- bayesplot theme set to bayesplot::theme_default()\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n   * Does _not_ affect other ggplot2 plots\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n   * See ?bayesplot_theme_set for details on theme setting\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'bayesplot'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:posterior':\n\n    rhat\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:brms':\n\n    rhat\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmcmc_intervals(\n  post_draws,\n  pars = \"b_Intercept\",\n  prob = 0.50,\n  prob_outer = 0.98\n)\n```\n\n::: {.cell-output-display}\n![](posterior-simulation_files/figure-pdf/unnamed-chunk-19-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nIt is often helpful to create a data frame for the simulated values of the parameter, but it's not necessary for all functions.\nFor example, we can just pass the `brms` output `fit` into `mcmc_areas`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmcmc_areas(\n  fit,\n  pars = \"b_Intercept\",\n  prob = 0.98\n)\n```\n\n::: {.cell-output-display}\n![](posterior-simulation_files/figure-pdf/unnamed-chunk-20-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\nThe `ggdist` package includes some add-ons for `ggplot2` that are useful for visualizing posterior distributions.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nposterior_df |>\n  ggplot(aes(x = theta)) +\n  stat_halfeye(.width = c(0.80, 0.98)) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](posterior-simulation_files/figure-pdf/unnamed-chunk-21-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n\n\n### Example: inference for a population mean\n\n\nNow we'll look at an example with continuous data.\nRecall @exm-temp-data.\nAssume body temperatures (degrees Fahrenheit) of healthy adults follow a Normal distribution with unknown mean $\\theta$ and known standard deviation $\\sigma=1$.\n(It's unrealistic to assume the population standard deviation is known.\nWe'll consider the case of unknown standard deviation later.)\nSuppose we wish to estimate $\\theta$, the population mean healthy human body temperature.\nWe considered a few priors in @exm-temp-data; here we'll use a Uniform prior on [96.0, 100.0].\nIn a recent study, the sample mean body temperature in a sample of 208 healthy adults was 97.7 degrees F.\n\nFirst we load the data from the file `bodytemps.csv`; the temperature variable is `bodytemp`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata = read_csv(\"bodytemps.csv\")\n\nhead(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 x 1\n  bodytemp\n     <dbl>\n1     95.6\n2     97.3\n3     98.0\n4     97.0\n5     96.0\n6     98.6\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata |>\n  ggplot(aes(x = bodytemp)) +\n  geom_histogram(aes(y = after_stat(density)), col = \"black\", fill = \"white\") +\n  geom_density(linewidth = 1) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](posterior-simulation_files/figure-pdf/unnamed-chunk-23-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nNext we fit the model to the data using the function `brm`.\nThe three inputs are\n\n\n-   Input 1: the data  \n    `data = data`\n\n-   Input 2: model for the data (likelihood)  \n    `family = gaussian`  \n    `bodytemp ~ 1 # linear model with intercept (mean) only`\n\n-   Input 3: prior distribution for parameters  \n    `prior = c(prior(uniform(96, 100), lb = 96, ub = 100, class = Intercept),`\n    `          prior(constant(1), class = sigma))`\n\n    Note that the Normal (`gaussian`) model for the likelihood assumes two parameters - mean (\"intercept\") and SD (\"sigma\") - so we need to specify a prior distribution for both parameters.\n    Since we're assuming that SD $\\sigma$ is known, we fix its value to be constant.\n\n-   Other arguments specify the details of the numerical algorithm; our specifications below will result in 10000 $(\\mu, \\sigma)$ pairs simulated from the posterior distribution; a few simulated values are displayed below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- brm(\n  data = data,\n  family = gaussian,\n  bodytemp ~ 1,\n  prior = c(\n    prior(uniform(96, 100), lb = 96, ub = 100, class = Intercept),\n    prior(constant(1), class = sigma)\n  ),\n  iter = 11000,\n  warmup = 1000,\n  chains = 1,\n  refresh = 0\n)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCompiling Stan program...\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nStart sampling\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: gaussian \n  Links: mu = identity \nFormula: bodytemp ~ 1 \n   Data: data (Number of observations: 208) \n  Draws: 1 chains, each with iter = 11000; warmup = 1000; thin = 1;\n         total post-warmup draws = 10000\n\nRegression Coefficients:\n          Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept    97.70      0.07    97.56    97.84 1.00     3398     5149\n\nFurther Distributional Parameters:\n      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsigma     1.00      0.00     1.00     1.00   NA       NA       NA\n\nDraws were sampled using sampling(NUTS). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(fit)\n```\n\n::: {.cell-output-display}\n![](posterior-simulation_files/figure-pdf/unnamed-chunk-26-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\nBelow we save simulated values of `theta` in the `posterior` data frame.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nposterior_df = fit |>\n  spread_draws(b_Intercept) |>\n  rename(theta = b_Intercept)\n\nposterior_df |> head(10) |> kbl() |> kable_styling()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}[t]{r|r|r|r}\n\\hline\n.chain & .iteration & .draw & theta\\\\\n\\hline\n1 & 1 & 1 & 97.72555\\\\\n\\hline\n1 & 2 & 2 & 97.77847\\\\\n\\hline\n1 & 3 & 3 & 97.66969\\\\\n\\hline\n1 & 4 & 4 & 97.66969\\\\\n\\hline\n1 & 5 & 5 & 97.76707\\\\\n\\hline\n1 & 6 & 6 & 97.75985\\\\\n\\hline\n1 & 7 & 7 & 97.71054\\\\\n\\hline\n1 & 8 & 8 & 97.71290\\\\\n\\hline\n1 & 9 & 9 & 97.71290\\\\\n\\hline\n1 & 10 & 10 & 97.71290\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n\n\n:::\n:::\n\n\nHere is a histogram of the simulated $\\theta$ values, with the approximate posterior density overlaid.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nposterior_df |>\n  ggplot(aes(x = theta)) +\n  geom_histogram(\n    aes(y = after_stat(density)),\n    col = bayes_col[\"posterior\"],\n    fill = \"white\"\n  ) +\n  geom_density(linewidth = 1, col = bayes_col[\"posterior\"]) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](posterior-simulation_files/figure-pdf/unnamed-chunk-28-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\nHere is a plot of the approximate posterior cumulative distribution function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nposterior_df |>\n  ggplot(aes(x = theta)) +\n  stat_ecdf(col = bayes_col[\"posterior\"], linewidth = 1) +\n  labs(title = \"Posterior cdf of theta\", y = \"Cumulative probability\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](posterior-simulation_files/figure-pdf/unnamed-chunk-29-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nWe can use the simulated values to approximate posterior mean and SD as usual.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(posterior_df$theta)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 97.69839\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsd(posterior_df$theta)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.07100237\n```\n\n\n:::\n:::\n\n\n\nQuantiles of the posterior distribution of $\\theta$ are endpoints of credible intervals.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquantile(posterior_df$theta, c(0.01, 0.10, 0.25, 0.75, 0.90, 0.99))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      1%      10%      25%      75%      90%      99% \n97.53385 97.60752 97.65134 97.74642 97.78925 97.86235 \n```\n\n\n:::\n:::\n\n\nWe can approximate the posterior probability that $\\theta$ is less than 97.8.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(posterior_df$theta < 97.8) / length(posterior_df$theta)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9233\n```\n\n\n:::\n:::\n\n\n\nA few more summaries.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmcmc_intervals(\n  posterior_df,\n  pars = \"theta\",\n  prob = 0.50,\n  prob_outer = 0.98\n)\n```\n\n::: {.cell-output-display}\n![](posterior-simulation_files/figure-pdf/unnamed-chunk-34-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmcmc_areas(\n  fit,\n  pars = \"b_Intercept\",\n  prob = 0.98\n)\n```\n\n::: {.cell-output-display}\n![](posterior-simulation_files/figure-pdf/unnamed-chunk-35-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nposterior_df |>\n  ggplot(aes(x = theta)) +\n  stat_halfeye(.width = c(0.80, 0.98)) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](posterior-simulation_files/figure-pdf/unnamed-chunk-36-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n### Example: Posterior predictive distribution and checking\n\nContinuing the body temperature example, we can use the simulated values of $\\theta$ to approximate the posterior predictive distribution.\nFor each simulated value of $\\theta$, simulate a $y$ value from a Normal($\\theta$, 1) distribution, and summarize the simulate $y$ values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_rep = length(posterior_df$theta)\n\ny_sim = rnorm(n_rep, posterior_df$theta, sd = 1)\n\nggplot(data.frame(y_sim), aes(x = y_sim)) +\n  geom_histogram(\n    aes(y = after_stat(density)),\n    col = bayes_col[\"posterior_predict\"],\n    fill = \"white\",\n    bins = 100\n  ) +\n  geom_density(linewidth = 1, col = bayes_col[\"posterior_predict\"]) +\n  labs(x = \"Predicted body temp\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](posterior-simulation_files/figure-pdf/unnamed-chunk-37-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nQuantiles of the posterior predictive distribution of $y$ are endpoints of posterior prediction intervals.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquantile(posterior_df$theta, c(0.025, 0.975))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    2.5%    97.5% \n97.55831 97.83618 \n```\n\n\n:::\n:::\n\n\n\nWe can use `pp_check` to perform a posterior predictive check: simulate hypothetical samples of size 208 according to the model, and compare to the observed data.\nThe plot below contains a histogram of predicted $y$ values for each of the simulated samples, along with a histogram of the observed data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npp_check(fit, type = \"hist\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nUsing 10 posterior draws for ppc type 'hist' by default.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](posterior-simulation_files/figure-pdf/unnamed-chunk-39-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nThe default plot output of `pp_check` displays the density of each of the simulated samples overlaid on the estimated density of the observed sample data.\nNote that `ndraws` is the number of simulated *samples*, each sample of size 208.\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npp_check(fit, ndraw = 100)\n```\n\n::: {.cell-output-display}\n![](posterior-simulation_files/figure-pdf/unnamed-chunk-40-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}