{
  "hash": "e6745bc303cfb013ca9962cc3c1755a2",
  "result": {
    "engine": "knitr",
    "markdown": "# Naive Bayes Classification {#sec-classification}\n\n\n\n\n\n\n\n<!-- {{< include _python_setup.qmd >}} -->\n\n\nWe have seen how to fit Bayesian regression models for predicting numerical variables.\nNow we will introduce a Bayesian *classification* method for predicting *categorical* variables.\nThe goal is to \"classify\" observations according to which category (class) they belong to.\n\n\n*This handout corresponds to [Chapter 14](https://www.bayesrulesbook.com/chapter-14.html) of [@johnson2022].*\n\n\n\nThere exist multiple penguin species throughout Antarctica, including the *Adelie* (A), *Chinstrap* (C), and *Gentoo* (G).\nOur goal will be to classify penguins according to their species given characteristics like weight or bill length.\n(Throughout \"penguin\" refers to an Antarctic penguin of one of these three species.)\n\n\n\n::: {#exm-classification-prior}\nSuppose first that we have no information about a randomly selected penguin (other than it's an Antarctic penguin from one of these three species).\n:::\n\n1. How might we formulate a prior distribution for the species of the penguin?\nWould we necessarily assume equal prior probability for the three species?\n\\\n\\\n\\\n\\\n\\\n\n1. Suppose that among Antarctic penguins of these three species, 44.2% of Adelie, 19.8% are Chinstrap, and 36.0% are Gentoo.\nStart to set up a Bayes table.\n\\\n\\\n\\\n\\\n\\\n\n\n\n::: {#exm-classification-categorical-predictor}\nNow suppose we know that a randomly selected penguin is below average weight (that is, below 4200g).\n:::\n\n1. What is the next column of the Bayes table to fill in?\nWhat information would we need to do so?\n\\\n\\\n\\\n\\\n\\\n\n1. Suppose that 83.4% of Adelie penguins are below average weight, 89.7% of Chinstrap penguins are below average weight, and 4.9% of Gentoo penguins are below average weight.\nAmong these three species, the likelihood of being below average weight is greatest for Chinstrap. \nDoes that mean we should necessarily classify the penguin to be Chinstrap?\nWhy?\n\\\n\\\n\\\n\\\n\\\n\n1. Complete the Bayes table and find the posterior probability of each species given that the penguin is below average weight.\n\\\n\\\n\\\n\\\n\\\n\n1. If the penguin is below average weight, what species would you classify it as?\nWhy?\n\\\n\\\n\\\n\\\n\\\n\n1. Now suppose the the penguin is not below average weight.\nCompute the posterior probability of each species given that the penguin is not below average weight.\nWhat species would you classify it as?\nWhy?\n\\\n\\\n\\\n\\\n\\\n\n1. Suppose that you classify any randomly selected penguin based on whether or not it is below average weight.\nWhat is the posterior probability that you classify the penguin correctly?\n\\\n\\\n\\\n\\\n\\\n\n\n\n::: {#exm-classification-numerical-predictor}\nNow suppose we know that a randomly selected penguin has a bill length of 50mm.\nWe'll start by assuming we don't know yet whether or not it is below average weight.\n:::\n\n1. Start to create a Bayes table.\nWhat is the prior?\nWhat is the next column of the Bayes table to fill in?\nWhat information would we need to do so?\n\\\n\\\n\\\n\\\n\\\n\n1. Suppose that bill lengths (mm) follow a N(38.8, 2.66) distribution for Adelie, a N(48.8, 3.34) distribution for Chinstrap, and a N(47.5, 3.08) distribution for Gentoo.\nHow would you fill in the likelihood column?\n\\\n\\\n\\\n\\\n\\\n\n1. Among these three species, the likelihood of having of a 50mm bill is greatest for Chinstrap.\nDoes that mean we should necessarily classify the penguin to be Chinstrap?\nWhy?\n\\\n\\\n\\\n\\\n\\\n\n1. Complete the Bayes table and find the posterior probability of each species given that the penguin has a 50mm bill.\n\\\n\\\n\\\n\\\n\\\n\n1. If the species has a 50mm bill, what species would you classify it as?\nWhy?\n\\\n\\\n\\\n\\\n\\\n\n1. Now suppose before measuring bill length we had already known that the penguin was below average weight.\nHow would our Bayes table have changed?\nIf we don't change the likelihood column, what are we assuming?\n\\\n\\\n\\\n\\\n\\\n\n\n1. Compute the posterior probability of each species given that the penguin is below average weight with a 50mm bill, assuming conditional independence between weight and bill length.\nGiven a species with these characteristics, what species would you classify it as?\nWhy?\n\\\n\\\n\\\n\\\n\\\n\n\n\n\n- **Naive Bayes classification** uses Bayes rule to predict the class of a categorical response variable $y$ given predictor variables $x_1, \\ldots, x_p$\n- Predictor variables can be categorical or numerical\n- Naive Bayes classification assumes that predictors are *conditionally independent* given each class\n- Naive Bayes classification typically assumes that any numerical predictor variable is conditionally Normal\n- Given observed data\n    - Prior probabilities for the response variable are estimated to be the observed sample proportion for each class\n    - For a categorical predictor $x$, the likelihood of value $\\tilde{x}$ is estimated to be the observed sample proportion of $\\tilde{x}$ within each class\n    - For a numerical predictor $x$, the likelihood is computed assuming that within each class values of the predictor follow a Normal distribution with mean and SD estimated to be the sample mean and SD within each class.\n\n\n\n::: {#exm-classification-two-predictors}\nNow suppose we know that a penguin has a bill length of 50mm and a flipper length of 195mm.\n(We'll ignore whether or not it is below average weight for this example.)\n:::\n\n1. Starting with our original prior, what is the \"evidence\" that the likelihood is based on?\nWhat information do we need to fill in the likelihood column?\n\\\n\\\n\\\n\\\n\\\n\n1. Suppose that flipper lengths (mm) follow a N(190, 6.54) distribution for Adelie, a N(196, 7.13) distribution for Chinstrap, and a N(217, 6.48) distribution for Gentoo.\n(Recall that bill lengths (mm) follow a N(38.8, 2.66) distribution for Adelie, a N(48.8, 3.34) distribution for Chinstrap, and a N(47.5, 3.08) distribution for Gentoo.)\nHow would you fill in the likelihood column?\nWhat are we assuming?\n\\\n\\\n\\\n\\\n\\\n\n\n\n1. Complete the Bayes table and find the posterior probability of each species given that the penguin has a 50mm bill and a 195mm flipper.\n\\\n\\\n\\\n\\\n\\\n\n1. If the species has a 50mm bill and a 195mm flipper, what species would you classify it as?\nWhy?\n\\\n\\\n\\\n\\\n\\\n\n\n\n\n\n\n\n\n\n## Notes\n\n### Given below average weight\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass = c(\"A\", \"C\", \"G\")\n\nprior = c(0.442, 0.198, 0.360)\n\n# likelihood of below average weight (evidence) given each species (class)\nlikelihood = c(0.834, 0.897, 0.049) \n\nproduct = prior * likelihood\n\nposterior = product / sum(product)\n\nposterior_given_below_average_weight = posterior\n\nbayes_table = data.frame(class,\n                         prior,\n                         likelihood,\n                         product,\n                         posterior)\n\nbayes_table |>\n  adorn_totals(\"row\") |>\n  kbl(digits = 4) |>\n  kable_styling()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}[t]{l|r|r|r|r}\n\\hline\nclass & prior & likelihood & product & posterior\\\\\n\\hline\nA & 0.442 & 0.834 & 0.3686 & 0.6537\\\\\n\\hline\nC & 0.198 & 0.897 & 0.1776 & 0.3150\\\\\n\\hline\nG & 0.360 & 0.049 & 0.0176 & 0.0313\\\\\n\\hline\nTotal & 1.000 & 1.780 & 0.5639 & 1.0000\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n\n\n:::\n:::\n\n\n### Given not below average weight\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass = c(\"A\", \"C\", \"G\")\n\nprior = c(0.442, 0.198, 0.360)\n\n# likelihood of not below average weight (evidence) given each species (class)\nlikelihood = c(1 - 0.834, 1 - 0.897, 1 - 0.049) \n\nproduct = prior * likelihood\n\nposterior = product / sum(product)\n\nbayes_table = data.frame(class,\n                         prior,\n                         likelihood,\n                         product,\n                         posterior)\n\nbayes_table |>\n  adorn_totals(\"row\") |>\n  kbl(digits = 4) |>\n  kable_styling()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}[t]{l|r|r|r|r}\n\\hline\nclass & prior & likelihood & product & posterior\\\\\n\\hline\nA & 0.442 & 0.166 & 0.0734 & 0.1682\\\\\n\\hline\nC & 0.198 & 0.103 & 0.0204 & 0.0468\\\\\n\\hline\nG & 0.360 & 0.951 & 0.3424 & 0.7850\\\\\n\\hline\nTotal & 1.000 & 1.220 & 0.4361 & 1.0000\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n\n\n:::\n:::\n\n\n### Given 50mm bill\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass = c(\"A\", \"C\", \"G\")\n\nprior = c(0.442, 0.198, 0.360)\n\n# likelihood of 50mm bill (evidence) given each species (class)\nlikelihood = c(dnorm(50, 38.8, 2.66),\n               dnorm(50, 48.8, 3.34),\n               dnorm(50, 47.5, 3.08))\n\nproduct = prior * likelihood\n\nposterior = product / sum(product)\n\nbayes_table = data.frame(class,\n                         prior,\n                         likelihood,\n                         product,\n                         posterior)\n\nbayes_table |>\n  adorn_totals(\"row\") |>\n  kbl(digits = 4) |>\n  kable_styling()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}[t]{l|r|r|r|r}\n\\hline\nclass & prior & likelihood & product & posterior\\\\\n\\hline\nA & 0.442 & 0.0000 & 0.0000 & 0.0002\\\\\n\\hline\nC & 0.198 & 0.1120 & 0.0222 & 0.3979\\\\\n\\hline\nG & 0.360 & 0.0932 & 0.0335 & 0.6019\\\\\n\\hline\nTotal & 1.000 & 0.2052 & 0.0557 & 1.0000\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n\n\n:::\n:::\n\n\n\n### Given 50mm bill and below average weight\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass = c(\"A\", \"C\", \"G\")\n\nprior = posterior_given_below_average_weight\n\n# likelihood of 50mm (evidence) given each species (class)\nlikelihood = c(dnorm(50, 38.8, 2.66),\n               dnorm(50, 48.8, 3.34),\n               dnorm(50, 47.5, 3.08))\n\nproduct = prior * likelihood\n\nposterior = product / sum(product)\n\nbayes_table = data.frame(class,\n                         prior,\n                         likelihood,\n                         product,\n                         posterior)\n\nbayes_table |>\n  adorn_totals(\"row\") |>\n  kbl(digits = 4) |>\n  kable_styling()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}[t]{l|r|r|r|r}\n\\hline\nclass & prior & likelihood & product & posterior\\\\\n\\hline\nA & 0.6537 & 0.0000 & 0.0000 & 0.0004\\\\\n\\hline\nC & 0.3150 & 0.1120 & 0.0353 & 0.9233\\\\\n\\hline\nG & 0.0313 & 0.0932 & 0.0029 & 0.0763\\\\\n\\hline\nTotal & 1.0000 & 0.2052 & 0.0382 & 1.0000\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n\n\n:::\n:::\n\n\n\n\n### Given 50mm bill and 195mm flipper\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass = c(\"A\", \"C\", \"G\")\n\nprior = c(0.442, 0.198, 0.360)\n\n# likelihood of 50mm bill (evidence) given each species (class)\nlikelihood_bill = c(dnorm(50, 38.8, 2.66),\n                    dnorm(50, 48.8, 3.34),\n                    dnorm(50, 47.5, 3.08))\n\n# likelihood of 195mm flipper (evidence) given each species (class)\nlikelihood_flipper = c(dnorm(195, 190, 6.54),\n                       dnorm(195, 196, 7.13),\n                       dnorm(195, 217, 6.48))\n\n# assume conditional independence of bill and flipper given species (class)\nlikelihood = likelihood_bill * likelihood_flipper\n\nproduct = prior * likelihood\n\nposterior = product / sum(product)\n\nbayes_table = data.frame(class,\n                         prior,\n                         likelihood_bill,\n                         likelihood_flipper,\n                         likelihood,\n                         product,\n                         posterior)\n\nbayes_table |>\n  adorn_totals(\"row\") |>\n  kbl(digits = 6) |>\n  kable_styling()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}[t]{l|r|r|r|r|r|r}\n\\hline\nclass & prior & likelihood\\_bill & likelihood\\_flipper & likelihood & product & posterior\\\\\n\\hline\nA & 0.442 & 0.000021 & 0.045542 & 0.000001 & 0.000000 & 0.000345\\\\\n\\hline\nC & 0.198 & 0.111978 & 0.055405 & 0.006204 & 0.001228 & 0.994404\\\\\n\\hline\nG & 0.360 & 0.093174 & 0.000193 & 0.000018 & 0.000006 & 0.005251\\\\\n\\hline\nTotal & 1.000 & 0.205173 & 0.101140 & 0.006223 & 0.001235 & 1.000000\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n\n\n:::\n:::\n\n\n### Data\n\n*This code is taken from [Chapter 14](https://www.bayesrulesbook.com/chapter-14.html) of [@johnson2022].*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(bayesrules)\n\n\n# Load data\ndata(penguins_bayes)\npenguins <- penguins_bayes\n\nhead(penguins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 x 9\n  species island     year bill_length_mm bill_depth_mm flipper_length_mm\n  <fct>   <fct>     <int>          <dbl>         <dbl>             <int>\n1 Adelie  Torgersen  2007           39.1          18.7               181\n2 Adelie  Torgersen  2007           39.5          17.4               186\n3 Adelie  Torgersen  2007           40.3          18                 195\n4 Adelie  Torgersen  2007           NA            NA                  NA\n5 Adelie  Torgersen  2007           36.7          19.3               193\n6 Adelie  Torgersen  2007           39.3          20.6               190\n# i 3 more variables: body_mass_g <int>, above_average_weight <fct>, sex <fct>\n```\n\n\n:::\n:::\n\n\nEstimated prior distribution\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins |>\n  tabyl(species)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   species   n   percent\n    Adelie 152 0.4418605\n Chinstrap  68 0.1976744\n    Gentoo 124 0.3604651\n```\n\n\n:::\n:::\n\n\nEstimated likelihood of below average weight\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins |>\n  select(species, above_average_weight) |>\n  na.omit() |>\n  tabyl(species, above_average_weight) |>\n  adorn_totals(c(\"row\", \"col\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   species   0   1 Total\n    Adelie 126  25   151\n Chinstrap  61   7    68\n    Gentoo   6 117   123\n     Total 193 149   342\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(penguins |>\n         drop_na(above_average_weight), \n       aes(fill = above_average_weight,\n           x = species)) + \n  geom_bar(position = \"fill\")\n```\n\n::: {.cell-output-display}\n![](classification_files/figure-pdf/unnamed-chunk-11-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\nEstimated likelihood of 50mm bill\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(penguins,\n       aes(x = bill_length_mm,\n           col = species)) + \n  geom_density(linewidth = 1) + \n  geom_vline(xintercept = 50, linetype = \"dashed\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 2 rows containing non-finite outside the scale range\n(`stat_density()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](classification_files/figure-pdf/unnamed-chunk-12-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins |>\n  group_by(species) |>\n  summarize(mean = mean(bill_length_mm, na.rm = TRUE), \n            sd = sd(bill_length_mm, na.rm = TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 x 3\n  species    mean    sd\n  <fct>     <dbl> <dbl>\n1 Adelie     38.8  2.66\n2 Chinstrap  48.8  3.34\n3 Gentoo     47.5  3.08\n```\n\n\n:::\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(penguins, aes(x = bill_length_mm, color = species)) + \n  stat_function(fun = dnorm, args = list(mean = 38.8, sd = 2.66), \n                aes(color = \"Adelie\")) +\n  stat_function(fun = dnorm, args = list(mean = 48.8, sd = 3.34),\n                aes(color = \"Chinstrap\")) +\n  stat_function(fun = dnorm, args = list(mean = 47.5, sd = 3.08),\n                aes(color = \"Gentoo\")) + \n  geom_vline(xintercept = 50, linetype = \"dashed\")\n```\n\n::: {.cell-output-display}\n![](classification_files/figure-pdf/unnamed-chunk-14-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\nEstimated likelihood of 195mm bill\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(penguins,\n       aes(x = flipper_length_mm,\n           col = species)) + \n  geom_density(linewidth = 1) + \n  geom_vline(xintercept = 195, linetype = \"dashed\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 2 rows containing non-finite outside the scale range\n(`stat_density()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](classification_files/figure-pdf/unnamed-chunk-15-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins |>\n  group_by(species) |>\n  summarize(mean = mean(flipper_length_mm, na.rm = TRUE), \n            sd = sd(flipper_length_mm, na.rm = TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 x 3\n  species    mean    sd\n  <fct>     <dbl> <dbl>\n1 Adelie     190.  6.54\n2 Chinstrap  196.  7.13\n3 Gentoo     217.  6.48\n```\n\n\n:::\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(penguins,\n       aes(x = flipper_length_mm,\n           color = species)) + \n  stat_function(fun = dnorm, args = list(mean = 190, sd = 6.54), \n                aes(color = \"Adelie\")) +\n  stat_function(fun = dnorm, args = list(mean = 196, sd = 7.13),\n                aes(color = \"Chinstrap\")) +\n  stat_function(fun = dnorm, args = list(mean = 217, sd = 6.48),\n                aes(color = \"Gentoo\")) + \n  geom_vline(xintercept = 195, linetype = \"dashed\")\n```\n\n::: {.cell-output-display}\n![](classification_files/figure-pdf/unnamed-chunk-17-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nFlipper length and bill length\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(penguins,\n       aes(x = flipper_length_mm,\n           y = bill_length_mm,\n           color = species)) + \n  geom_point()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 2 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](classification_files/figure-pdf/unnamed-chunk-18-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n### Naive Bayes Classification with `e1071` package\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(e1071)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'e1071'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:ggplot2':\n\n    element\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nour_penguin <- data.frame(above_average_weight = \"0\",\n                          bill_length_mm = 50,\n                          flipper_length_mm = 195)\n```\n:::\n\n\n\n#### Given below average weight\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnaive_model_weight = naiveBayes(species ~ above_average_weight,\n                                data = penguins)\n\nnaive_model_weight\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nNaive Bayes Classifier for Discrete Predictors\n\nCall:\nnaiveBayes.default(x = X, y = Y, laplace = laplace)\n\nA-priori probabilities:\nY\n   Adelie Chinstrap    Gentoo \n0.4418605 0.1976744 0.3604651 \n\nConditional probabilities:\n           above_average_weight\nY                    0          1\n  Adelie    0.83443709 0.16556291\n  Chinstrap 0.89705882 0.10294118\n  Gentoo    0.04878049 0.95121951\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(naive_model_weight,\n        newdata = our_penguin,\n        type = \"raw\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        Adelie Chinstrap     Gentoo\n[1,] 0.6541796 0.3146224 0.03119806\n```\n\n\n:::\n:::\n\n\n\n\n#### Given 50mm bill\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnaive_model_bill = naiveBayes(species ~ bill_length_mm,\n                                data = penguins)\n\nnaive_model_bill\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nNaive Bayes Classifier for Discrete Predictors\n\nCall:\nnaiveBayes.default(x = X, y = Y, laplace = laplace)\n\nA-priori probabilities:\nY\n   Adelie Chinstrap    Gentoo \n0.4418605 0.1976744 0.3604651 \n\nConditional probabilities:\n           bill_length_mm\nY               [,1]     [,2]\n  Adelie    38.79139 2.663405\n  Chinstrap 48.83382 3.339256\n  Gentoo    47.50488 3.081857\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(naive_model_bill,\n        newdata = our_penguin,\n        type = \"raw\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           Adelie Chinstrap    Gentoo\n[1,] 0.0001690279 0.3978306 0.6020004\n```\n\n\n:::\n:::\n\n\n\n#### Given 50mm bill and below average weight\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnaive_model_weight_and_bill = naiveBayes(species ~ above_average_weight + bill_length_mm,\n                                         data = penguins)\n\nnaive_model_weight_and_bill\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nNaive Bayes Classifier for Discrete Predictors\n\nCall:\nnaiveBayes.default(x = X, y = Y, laplace = laplace)\n\nA-priori probabilities:\nY\n   Adelie Chinstrap    Gentoo \n0.4418605 0.1976744 0.3604651 \n\nConditional probabilities:\n           above_average_weight\nY                    0          1\n  Adelie    0.83443709 0.16556291\n  Chinstrap 0.89705882 0.10294118\n  Gentoo    0.04878049 0.95121951\n\n           bill_length_mm\nY               [,1]     [,2]\n  Adelie    38.79139 2.663405\n  Chinstrap 48.83382 3.339256\n  Gentoo    47.50488 3.081857\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(naive_model_weight_and_bill,\n        newdata = our_penguin,\n        type = \"raw\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           Adelie Chinstrap     Gentoo\n[1,] 0.0003650334 0.9236333 0.07600171\n```\n\n\n:::\n:::\n\n\n\n#### Given 50mm bill and 195mm flipper\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnaive_model_flipper_and_bill = naiveBayes(species ~ flipper_length_mm + bill_length_mm,\n                                          data = penguins)\n\nnaive_model_flipper_and_bill\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nNaive Bayes Classifier for Discrete Predictors\n\nCall:\nnaiveBayes.default(x = X, y = Y, laplace = laplace)\n\nA-priori probabilities:\nY\n   Adelie Chinstrap    Gentoo \n0.4418605 0.1976744 0.3604651 \n\nConditional probabilities:\n           flipper_length_mm\nY               [,1]     [,2]\n  Adelie    189.9536 6.539457\n  Chinstrap 195.8235 7.131894\n  Gentoo    217.1870 6.484976\n\n           bill_length_mm\nY               [,1]     [,2]\n  Adelie    38.79139 2.663405\n  Chinstrap 48.83382 3.339256\n  Gentoo    47.50488 3.081857\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(naive_model_flipper_and_bill,\n        newdata = our_penguin,\n        type = \"raw\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           Adelie Chinstrap      Gentoo\n[1,] 0.0003445688 0.9948681 0.004787365\n```\n\n\n:::\n:::\n\n\n\n#### Evaluation of flipper length and bill length model\n\nCan classify each of the penguins in the data set\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins <- penguins %>%\n  mutate(predicted_species = predict(naive_model_flipper_and_bill, newdata = .))\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins |> \n  select(bill_length_mm, flipper_length_mm, species, predicted_species) |>\n  head(10) |>\n  kbl() |> kable_styling()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}[t]{r|r|l|l}\n\\hline\nbill\\_length\\_mm & flipper\\_length\\_mm & species & predicted\\_species\\\\\n\\hline\n39.1 & 181 & Adelie & Adelie\\\\\n\\hline\n39.5 & 186 & Adelie & Adelie\\\\\n\\hline\n40.3 & 195 & Adelie & Adelie\\\\\n\\hline\nNA & NA & Adelie & Adelie\\\\\n\\hline\n36.7 & 193 & Adelie & Adelie\\\\\n\\hline\n39.3 & 190 & Adelie & Adelie\\\\\n\\hline\n38.9 & 181 & Adelie & Adelie\\\\\n\\hline\n39.2 & 195 & Adelie & Adelie\\\\\n\\hline\n34.1 & 193 & Adelie & Adelie\\\\\n\\hline\n42.0 & 190 & Adelie & Adelie\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n\n\n:::\n:::\n\n\nThen check classification against actual species to see how well the classification algorithm works within the sample.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins |>\n  tabyl(species, predicted_species) |>\n  adorn_percentages(\"row\") |>\n  adorn_pct_formatting(digits = 2) |>\n  adorn_ns()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   species       Adelie   Chinstrap       Gentoo\n    Adelie 96.05% (146)  2.63%  (4)  1.32%   (2)\n Chinstrap  7.35%   (5) 86.76% (59)  5.88%   (4)\n    Gentoo  0.81%   (1)  0.81%  (1) 98.39% (122)\n```\n\n\n:::\n:::\n\n\n\nWe can use cross-validation to estimate how well our algorithm would classify new penguins outside of the data set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnaive_cv <-\n  naive_classification_summary_cv(model = naive_model_flipper_and_bill,\n                                  data = penguins,\n                                  y = \"species\",\n                                  k = 10)\n\nnaive_cv$cv\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   species       Adelie   Chinstrap       Gentoo\n    Adelie 96.05% (146)  2.63%  (4)  1.32%   (2)\n Chinstrap  7.35%   (5) 86.76% (59)  5.88%   (4)\n    Gentoo  0.81%   (1)  0.81%  (1) 98.39% (122)\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n",
    "supporting": [
      "classification_files\\figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}