{
  "hash": "c66392d43df3b974792f6172c3268f75",
  "result": {
    "engine": "knitr",
    "markdown": "# Introduction to Inference for a Population Mean {#sec-normal-mean}\n\n\n\n\n\n\n\n<!-- {{< include _python_setup.qmd >}} -->\n\n\n\n- Recall that the likelihood function is the probability (or density for continuous data) of observing the sample data $y$ viewed as a *function of the parameter* $\\theta$.\n- When the data $y$ takes values on a  continuous scale, the likelihood is determined by the *probability density function* of $y$ given $\\theta$, $f(y|\\theta)$.\n- In the likelihood function, the observed value of the data $y$ is treated as a fixed constant, and the likelihood of observing that $y$ is evaluated for all potential values of $\\theta$.\n\n\n::: {#exm-temp-setup}\nAssume body temperatures (degrees Fahrenheit) of healthy adults follow a Normal distribution with unknown mean $\\theta$ and known standard deviation $\\sigma=1.1$.\n(It's unrealistic to assume the population standard deviation is known.\nWe'll consider the case of unknown standard deviation later.)\nSuppose we wish to estimate $\\theta$, the population mean healthy human body temperature.  \n\n:::\n\n1. If $\\theta$ was known (say $\\theta = 98.6$), what would the distribution of $y$ look like?\nWhat are some of its features?\nWhat does the standard deviation $\\sigma=1.1$ represent?\n\\\n\\\n\\\n\\\n\\\n\n1. Sketch your prior distribution for $\\theta$.\nWhat is your single most plausible value for $\\theta$?\nAbout what range of values accounts for most (say 98%) of your prior plausibility?\nRoughly, what is your prior standard deviation?\nWhat does your prior standard deviation represent?\n\\\n\\\n\\\n\\\n\\\n\nBe careful to distinguish between\n\n- Model for the data\n    - The conditional distribution of the measured variables $y$ given the parameters $\\theta$, which determines (once the data are observed) the likelihood\n    - The model for the data represents our assumptions about how the measured variables $y$ vary from unit-to-unit in the population\n- Prior model for parameters\n    - The prior (marginal) distribution of the parameters $\\theta$ which are present in the model for the data\n    - The prior distribution represents --- via a probability distribution --- our assessment of plausibility/uncertainty of values of parameters $\\theta$ prior to observing sample data\n\n\n::: {#exm-temp-discrete}\nContinuing @exm-temp-setup.\nAssume first a discrete prior distribution for $\\theta$ which places probability 0.10, 0.25, 0.30, 0.25, 0.10 on the values 97.6, 98.1, 98.6, 99.1, 99.6, respectively.\n:::\n\n1. Suppose a single temperature value of 97.9 is observed.\nConstruct a Bayes table and find the posterior distribution of $\\theta$.\nIn particular, how do you determine the likelihood?\n\\\n\\\n\\\n\\\n\\\n\n1. Now suppose a second temperature value, 97.5, is observed, independently of the first.\nConstruct a Bayes table and find the posterior distribution of $\\theta$ after observing these two measurements, using the posterior distribution from the previous part as the prior distribution in this part.\n\\\n\\\n\\\n\\\n\\\n\n1. Now consider the original prior again.\nDetermine the likelihood of observing temperatures of 97.9 and 97.5 in a sample of size 2.\nThen construct a Bayes table, starting with the original prior, and find the posterior distribution of $\\theta$ after observing these two measurements.\nCompare to the previous part.\n\\\n\\\n\\\n\\\n\\\n\n1. Consider the original prior again.\nSuppose that we take a random sample of two temperature measurements, but instead of observing the two individual values, we only observe that the sample mean is 97.7.\nDetermine the likelihood of observing a sample mean of 97.7 in a sample of size 2.\n(Hint: if $\\bar{y}$ is the sample mean of $n$ values from a $N(\\theta, \\sigma)$ distribution, what is the distribution of $\\bar{y}$?)\nThen construct a Bayes table and find the posterior distribution of $\\theta$ after observing this sample mean 97.7.\nCompare to the previous part.\n\\\n\\\n\\\n\\\n\\\n\n\n\n\n- It is often not necessary to know all the individual data values to evaluate the *shape* of the likelihood as a function of the parameter $\\theta$, but rather simply the values of a few summary statistics.   \n\n::: {#exm-temp-grid}\nContinuing @exm-temp-setup.\nWe'll now use a grid approximation and assume that any multiple of 0.0001 between 96.0 and 100.0 is a possible value of $\\theta$: 96.0, 96.0001, 96.0002, $\\ldots$, 99.9999, 100.0.\n\nSuppose that the sample mean temperature is $\\bar{y}=97.7$ in a sample of $n=2$ temperature measurements.\n:::\n\n\n\n1. Assume a discrete uniform prior distribution over $\\theta$ values in the grid.\nUse software to plot the prior distribution, the (scaled) likelihood function, and then find the posterior and plot it.\nDescribe the posterior distribution.\nWhat does it say about $\\theta$?\n\\\n\\\n\\\n\\\n\\\n\n\n1. Assume a discrete triangular prior distribution which is proportional to $2 - |\\theta - 98.0|$ over $\\theta$ values in the grid.\nUse software to plot the prior distribution, the (scaled) likelihood function, and then find the posterior and plot it.\nDescribe the posterior distribution.\nWhat does it say about $\\theta$?\n\\\n\\\n\\\n\\\n\\\n\n1. Now assume a prior distribution which is proportional to a Normal distribution with mean 98.6 and standard deviation 0.3 over $\\theta$ values in the grid.\n(Careful: be sure not to confuse a Normal prior distribution with the likelihood.)\nUse software to plot the prior distribution, the (scaled) likelihood function, and then find the posterior and plot it.\nDescribe the posterior distribution.\nWhat does it say about $\\theta$?\n\\\n\\\n\\\n\\\n\\\n\n1. Compare the posterior distributions corresponding to the different priors.\nHow does each posterior distribution compare to the prior and the likelihood?\nComment on the influence that the prior distribution has.\n(But remember, this is only a sample of size $n=2$.)\n\\\n\\\n\\\n\\\n\\\n\n::: {#exm-temp-data}\nContinuing @exm-temp-setup.\nIn a recent study^[[Source](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6258625/) and a [related article](https://www.scientificamerican.com/article/are-human-body-temperatures-cooling-down/).], the sample mean body temperature in a sample of 208 healthy adults was 97.7 degrees F.\n\nWe'll again use a grid approximation and assume that any multiple of 0.0001 between 96.0 and 100.0 is a possible value of $\\theta$: $96.0, 96.0001, 96.0002, \\ldots, 99.9999, 100.0$.\n:::\n\n\n\n1. Assume a discrete uniform prior distribution over $\\theta$ values in the grid.\nUse software to plot the prior distribution, the (scaled) likelihood function, and then find the posterior and plot it.\nDescribe the posterior distribution.\nWhat does it say about $\\theta$?\n\\\n\\\n\\\n\\\n\\\n\n\n1. Assume a discrete triangular prior distribution which is proportional to $2 - |\\theta - 98.0|$ over $\\theta$ values in the grid.\nUse software to plot the prior distribution, the (scaled) likelihood function, and then find the posterior and plot it.\nDescribe the posterior distribution.\nWhat does it say about $\\theta$?\n\\\n\\\n\\\n\\\n\\\n\n1. Now assume a prior distribution which is proportional to a Normal distribution with mean 98.6 and standard deviation 0.3 over $\\theta$ values in the grid.\n(Careful: be sure not to confuse a Normal prior distribution with the likelihood.)\nUse software to plot the prior distribution, the (scaled) likelihood function, and then find the posterior and plot it.\nDescribe the posterior distribution.\nWhat does it say about $\\theta$?\n\\\n\\\n\\\n\\\n\\\n\n1. Compare the posterior distributions corresponding to the three different priors.\nHow does each posterior distribution compare to the prior and the likelihood?\nComment on the influence that the prior distribution has; how does this compare to the $n=2$ situation?\n\\\n\\\n\\\n\\\n\\\n\n\n1. The posterior distribution is approximately Normal with posterior mean 97.75 and posterior SD 0.074.\nExplain what the posterior SD represents.\n\\\n\\\n\\\n\\\n\\\n\n1. Compute *and interpret in context* the posterior probability that $\\theta$ is less than 98.6.\nCompare to the prior probability.\n\\\n\\\n\\\n\\\n\\\n\n1. Compute and *interpret in context* 50%, 80%, and 98% central posterior credible intervals for $\\theta$.\nCompare to the prior intervals.\n\\\n\\\n\\\n\\\n\\\n\n\n## Notes\n\n### Likelihood of single value\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](normal-mean_files/figure-pdf/unnamed-chunk-3-1.pdf)\n:::\n\n::: {.cell-output-display}\n![](normal-mean_files/figure-pdf/unnamed-chunk-3-2.pdf)\n:::\n:::\n\n\n\n### Posterior based on first observation and discrete prior\n\nThe likelihood is determined by evaluating the Normal($\\theta$, 1.1) density at $y=97.9$ for different values of $\\theta$: `dnorm(97.9, theta, 1.1)` or\n\n$$\nf(97.9|\\theta)  = \\frac{1}{\\sqrt{2\\pi}}\\,\\exp\\left(-\\frac{1}{2}\\left(\\frac{97.9-\\theta}{1.1}\\right)^2\\right)\n$$\n\nFor example, the likelihood for $\\theta = 98.6$ is\n\n$$\n\\frac{1}{\\sqrt{2\\pi}}\\,\\exp\\left(-\\frac{1}{2}\\left(\\frac{97.9-98.6}{1.1}\\right)^2\\right),\n$$\n\nor `dnorm(97.9, 98.6, 1.1)` = 0.296.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# possible values of theta\ntheta = seq(97.6, 99.6, 0.5)\n\n# prior\nprior = c(0.10, 0.25, 0.30, 0.25, 0.10)\nprior = prior / sum(prior)\n\n# observed data\ny = 97.9 # single observed value\nsigma = 1.1 # assumed known population SD\n\n# likelihood of observed data for each theta\nlikelihood = dnorm(y, theta, sigma)\n\n# posterior is proportional to product of prior and likelihood\nproduct = prior * likelihood\nposterior = product / sum(product)\n\nbayes_table = data.frame(theta, prior, likelihood, product, posterior)\n\nbayes_table |>\n  adorn_totals(\"row\") |>\n  kbl(digits = 4) |>\n  kable_styling()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}[t]{l|r|r|r|r}\n\\hline\ntheta & prior & likelihood & product & posterior\\\\\n\\hline\n97.6 & 0.10 & 0.3494 & 0.0349 & 0.1275\\\\\n\\hline\n98.1 & 0.25 & 0.3567 & 0.0892 & 0.3255\\\\\n\\hline\n98.6 & 0.30 & 0.2962 & 0.0889 & 0.3243\\\\\n\\hline\n99.1 & 0.25 & 0.2000 & 0.0500 & 0.1825\\\\\n\\hline\n99.6 & 0.10 & 0.1099 & 0.0110 & 0.0401\\\\\n\\hline\nTotal & 1.00 & 1.3123 & 0.2740 & 1.0000\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n\n\n:::\n:::\n\n\n\n### Posterior based on second observation and discrete prior\n\nThe likelihood is determined by evaluating the Normal($\\theta$, 1.1) density at $y=97.5$ for different values of $\\theta$: `dnorm(97.5, theta, 1.1)` or\n\n$$\nf(97.5|\\theta)  = \\frac{1}{\\sqrt{2\\pi}}\\,\\exp\\left(-\\frac{1}{2}\\left(\\frac{97.5-\\theta}{1.1}\\right)^2\\right)\n$$\n\nFor example, the likelihood for $\\theta = 98.6$ is\n\n$$\n\\frac{1}{\\sqrt{2\\pi}}\\,\\exp\\left(-\\frac{1}{2}\\left(\\frac{97.5-98.6}{1.1}\\right)^2\\right),\n$$\n\nor `dnorm(97.5, 98.6, 1.1)` = 0.220.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# prior is posterior from previous part\nprior = posterior\n\n# data\ny = 97.5 # second observed value\n\n# likelihood of observed data for each theta\nlikelihood = dnorm(y, theta, sigma)\n\n# posterior is proportional to product of prior and likelihood\nproduct = likelihood * prior\nposterior = product / sum(product)\n\n# bayes table\nbayes_table = data.frame(theta, prior, likelihood, product, posterior)\n\nbayes_table |>\n  adorn_totals(\"row\") |>\n  kbl(digits = 4) |>\n  kable_styling()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}[t]{l|r|r|r|r}\n\\hline\ntheta & prior & likelihood & product & posterior\\\\\n\\hline\n97.6 & 0.1275 & 0.3612 & 0.0461 & 0.1884\\\\\n\\hline\n98.1 & 0.3255 & 0.3125 & 0.1017 & 0.4161\\\\\n\\hline\n98.6 & 0.3243 & 0.2200 & 0.0713 & 0.2918\\\\\n\\hline\n99.1 & 0.1825 & 0.1259 & 0.0230 & 0.0940\\\\\n\\hline\n99.6 & 0.0401 & 0.0586 & 0.0024 & 0.0096\\\\\n\\hline\nTotal & 1.0000 & 1.0782 & 0.2445 & 1.0000\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n\n\n:::\n:::\n\n\n\n### Posterior based on two observations and discrete prior\n\nSince the two measurements are independent, the likelihood is the product of the likelihoods for $y=97.9$ and $y=97.5$: `dnorm(97.9, theta, 1.1) * dnorm(97.5, theta, 1.1)` or\n\n$$\nf((97.9, 97.5)|\\theta)  = \\left(\\frac{1}{\\sqrt{2\\pi}}\\,\\exp\\left(-\\frac{1}{2}\\left(\\frac{97.9-\\theta}{1.1}\\right)^2\\right)\\right)\\left(\\frac{1}{\\sqrt{2\\pi}}\\,\\exp\\left(-\\frac{1}{2}\\left(\\frac{97.5-\\theta}{1.1}\\right)^2\\right)\\right)\n$$\n\nFor example, the likelihood for $\\theta = 98.6$ is\n\n$$\nf((97.9, 97.5)|\\theta=98.6)  = \\left(\\frac{1}{\\sqrt{2\\pi}}\\,\\exp\\left(-\\frac{1}{2}\\left(\\frac{97.9-98.6}{1.1}\\right)^2\\right)\\right)\\left(\\frac{1}{\\sqrt{2\\pi}}\\,\\exp\\left(-\\frac{1}{2}\\left(\\frac{97.5-98.6}{1.1}\\right)^2\\right)\\right)\n$$\n\nor `dnorm(97.9, 98.6, 1.1) * dnorm(97.5, 98.6, 1.1)` = (0.296)(0.218) = 0.065.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# prior\nprior = c(0.10, 0.25, 0.30, 0.25, 0.10)\nprior = prior / sum(prior)\n\n# data\ny = c(97.9, 97.5) # two observed values\nsigma = 1.1\n\n\n# likelihood - function of theta\nlikelihood = dnorm(y[1], theta, sigma) * dnorm(y[2], theta, sigma)\n\n# posterior\nproduct = likelihood * prior\nposterior = product / sum(product)\n\n# bayes table\nbayes_table = data.frame(theta, prior, likelihood, product, posterior)\n\nbayes_table |>\n  adorn_totals(\"row\") |>\n  kbl(digits = 4) |>\n  kable_styling()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}[t]{l|r|r|r|r}\n\\hline\ntheta & prior & likelihood & product & posterior\\\\\n\\hline\n97.6 & 0.10 & 0.1262 & 0.0126 & 0.1884\\\\\n\\hline\n98.1 & 0.25 & 0.1115 & 0.0279 & 0.4161\\\\\n\\hline\n98.6 & 0.30 & 0.0652 & 0.0195 & 0.2918\\\\\n\\hline\n99.1 & 0.25 & 0.0252 & 0.0063 & 0.0940\\\\\n\\hline\n99.6 & 0.10 & 0.0064 & 0.0006 & 0.0096\\\\\n\\hline\nTotal & 1.00 & 0.3345 & 0.0670 & 1.0000\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n\n\n:::\n:::\n\n\n\n### Posterior based on sample mean of two observations and discrete prior\n\nFor a sample of size $n$ from a $N(\\theta,\\sigma)$ distribution, the sample mean $\\bar{y}$ follows a $N\\left(\\theta, \\frac{\\sigma}{\\sqrt{n}}\\right)$ distribution.\nRemember: $\\sigma/\\sqrt{n}$ represents the sample-to-sample variability of sample means.\n\nThe likelihood is determined by evaluating the Normal($\\theta$, $\\frac{1.1}{\\sqrt{2}}$) density at $\\bar{y}=97.7$ for different values of $\\theta$: `dnorm(97.7, theta, 1.1 / sqrt(2))` or\n\n$$\nf_{\\bar{Y}}(97.7|\\theta)  \\propto \\exp\\left(-\\frac{1}{2}\\left(\\frac{97.7-\\theta}{1.1/\\sqrt{2}}\\right)^2\\right)\n$$\n\nFor example, the likelihood for $\\theta = 98.6$ is\n\n$$\nf_{\\bar{Y}}((97.7)|\\theta=98.6)  \\propto \\exp\\left(-\\frac{1}{2}\\left(\\frac{97.7-98.6}{1.1/\\sqrt{2}}\\right)^2\\right)\n$$\n\nor `dnorm(97.7, 98.6, 1.1 / sqrt(2))` = 0.263.\n\nThe likelihood is *not* the same as in the previous part.\nThere are many samples with a sample mean of 97.7, of which the sample (97.9, 97.5) is only one possibility, so the likelihood of observing a sample mean of 97.7 is greater than the likelihood of (97.9, 97.5).\nHowever, while the likelihood is not the same as in the previous part, it is *proportionally* the same.\nThat is, the likelihood in this part has the same *shape* as the likelihood in the previous part.\nFor example, the ratio of the likelihoods for $\\theta=98.6$ and $\\theta=98.1$ is the same in both parts: $0.4494/0.2626 = 1.71$ and $0.1115/0.0652=1.71$.\nSince the prior distribution is the same in both parts, and the likelihoods are proportionally the same, then the posterior distributions are the same.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# prior\nprior = c(0.10, 0.25, 0.30, 0.25, 0.10)\nprior = prior / sum(prior)\n\n# data\nn = 2\ny = 97.7 # sample mean\nsigma = 1.1\n\n\n# likelihood\nlikelihood = dnorm(y, theta, sigma / sqrt(n)) # function of theta\n\n# posterior\nproduct = likelihood * prior\nposterior = product / sum(product)\n\n# bayes table\nbayes_table = data.frame(theta, prior, likelihood, product, posterior)\n\nbayes_table |>\n  adorn_totals(\"row\") |>\n  kbl(digits = 4) |>\n  kable_styling()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}[t]{l|r|r|r|r}\n\\hline\ntheta & prior & likelihood & product & posterior\\\\\n\\hline\n97.6 & 0.10 & 0.5087 & 0.0509 & 0.1884\\\\\n\\hline\n98.1 & 0.25 & 0.4494 & 0.1123 & 0.4161\\\\\n\\hline\n98.6 & 0.30 & 0.2626 & 0.0788 & 0.2918\\\\\n\\hline\n99.1 & 0.25 & 0.1015 & 0.0254 & 0.0940\\\\\n\\hline\n99.6 & 0.10 & 0.0260 & 0.0026 & 0.0096\\\\\n\\hline\nTotal & 1.00 & 1.3481 & 0.2700 & 1.0000\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n\n\n:::\n:::\n\n\n\n### Posterior based on sample of size $n=2$ and uniform prior\n\nThe only change is the grid and the prior.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntheta = seq(96, 100, 0.0001)\n\n# prior\nprior = rep(1, length(theta)) # shape of prior\nprior = prior / sum(prior) # scales so that prior sums to 1\n\n# data\nn = 2 # sample size\ny = 97.7 # sample mean\nsigma = 1.1 # assumed known\n\n# likelihood\nlikelihood = dnorm(y, theta, sigma / sqrt(n)) # function of theta\n\n# posterior\nproduct = likelihood * prior\nposterior = product / sum(product)\n\nbayes_table = data.frame(theta, prior, likelihood, product, posterior)\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbayes_table |>\n  # scale likelihood for plotting only\n  mutate(likelihood = likelihood / sum(likelihood)) |>\n  select(theta, prior, likelihood, posterior) |>\n  pivot_longer(!theta, names_to = \"source\", values_to = \"probability\") |>\n  mutate(source = fct_relevel(source, \"prior\", \"likelihood\", \"posterior\")) |>\n  ggplot(aes(x = theta, y = probability, col = source)) +\n  geom_line(aes(linetype = source), linewidth = 1) +\n  scale_color_manual(values = bayes_col) +\n  scale_linetype_manual(values = bayes_lty) +\n  theme_bw() +\n  # remove y-axis labels\n  theme(\n    axis.title.y = element_blank(),\n    axis.text.y = element_blank(),\n    axis.ticks.y = element_blank()\n  )\n```\n\n::: {.cell-output-display}\n![](normal-mean_files/figure-pdf/unnamed-chunk-9-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n### Posterior based on sample of size $n=2$ and triangular prior\n\nThe only change is the prior\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntheta = seq(96, 100, 0.0001)\n\n# prior\nprior = 2 - abs(theta - 98) # shape of prior\nprior = prior / sum(prior) # scales so that prior sums to 1\n\n# data\nn = 2 # sample size\ny = 97.7 # sample mean\nsigma = 1.1 # assumed known\n\n# likelihood\nlikelihood = dnorm(y, theta, sigma / sqrt(n)) # function of theta\n\n# posterior\nproduct = likelihood * prior\nposterior = product / sum(product)\n\nbayes_table = data.frame(theta, prior, likelihood, product, posterior)\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbayes_table |>\n  # scale likelihood for plotting only\n  mutate(likelihood = likelihood / sum(likelihood)) |>\n  select(theta, prior, likelihood, posterior) |>\n  pivot_longer(!theta, names_to = \"source\", values_to = \"probability\") |>\n  mutate(source = fct_relevel(source, \"prior\", \"likelihood\", \"posterior\")) |>\n  ggplot(aes(x = theta, y = probability, col = source)) +\n  geom_line(aes(linetype = source), linewidth = 1) +\n  scale_color_manual(values = bayes_col) +\n  scale_linetype_manual(values = bayes_lty) +\n  theme_bw() +\n  # remove y-axis labels\n  theme(\n    axis.title.y = element_blank(),\n    axis.text.y = element_blank(),\n    axis.ticks.y = element_blank()\n  )\n```\n\n::: {.cell-output-display}\n![](normal-mean_files/figure-pdf/unnamed-chunk-11-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n### Posterior based on sample of size $n=2$ and Normal prior\n\n\nThe only change is the prior\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntheta = seq(96, 100, 0.0001)\n\n# prior\nprior = dnorm(theta, 98.6, 0.3) # shape of prior\nprior = prior / sum(prior) # scales so that prior sums to 1\n\n# data\nn = 2 # sample size\ny = 97.7 # sample mean\nsigma = 1.1 # assumed known\n\n# likelihood\nlikelihood = dnorm(y, theta, sigma / sqrt(n)) # function of theta\n\n# posterior\nproduct = likelihood * prior\nposterior = product / sum(product)\n\nbayes_table = data.frame(theta, prior, likelihood, product, posterior)\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbayes_table |>\n  # scale likelihood for plotting only\n  mutate(likelihood = likelihood / sum(likelihood)) |>\n  select(theta, prior, likelihood, posterior) |>\n  pivot_longer(!theta, names_to = \"source\", values_to = \"probability\") |>\n  mutate(source = fct_relevel(source, \"prior\", \"likelihood\", \"posterior\")) |>\n  ggplot(aes(x = theta, y = probability, col = source)) +\n  geom_line(aes(linetype = source), linewidth = 1) +\n  scale_color_manual(values = bayes_col) +\n  scale_linetype_manual(values = bayes_lty) +\n  theme_bw() +\n  # remove y-axis labels\n  theme(\n    axis.title.y = element_blank(),\n    axis.text.y = element_blank(),\n    axis.ticks.y = element_blank()\n  )\n```\n\n::: {.cell-output-display}\n![](normal-mean_files/figure-pdf/unnamed-chunk-13-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n### Posterior based on sample of size $n=208$ and uniform prior\n\nThe only change is the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntheta = seq(96, 100, 0.0001)\n\n# prior\nprior = rep(1, length(theta)) # shape of prior\nprior = prior / sum(prior) # scales so that prior sums to 1\n\n# data\nn = 208 # sample size\ny = 97.7 # sample mean\nsigma = 1.1 # assumed known\n\n# likelihood\nlikelihood = dnorm(y, theta, sigma / sqrt(n)) # function of theta\n\n# posterior\nproduct = likelihood * prior\nposterior = product / sum(product)\n\nbayes_table = data.frame(theta, prior, likelihood, product, posterior)\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbayes_table |>\n  # scale likelihood for plotting only\n  mutate(likelihood = likelihood / sum(likelihood)) |>\n  select(theta, prior, likelihood, posterior) |>\n  pivot_longer(!theta, names_to = \"source\", values_to = \"probability\") |>\n  mutate(source = fct_relevel(source, \"prior\", \"likelihood\", \"posterior\")) |>\n  ggplot(aes(x = theta, y = probability, col = source)) +\n  geom_line(aes(linetype = source), linewidth = 1) +\n  scale_color_manual(values = bayes_col) +\n  scale_linetype_manual(values = bayes_lty) +\n  theme_bw() +\n  # remove y-axis labels\n  theme(\n    axis.title.y = element_blank(),\n    axis.text.y = element_blank(),\n    axis.ticks.y = element_blank()\n  )\n```\n\n::: {.cell-output-display}\n![](normal-mean_files/figure-pdf/unnamed-chunk-15-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n### Posterior based on sample of size $n=208$ and triangular prior\n\nThe only change is the prior\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntheta = seq(96, 100, 0.0001)\n\n# prior\nprior = 2 - abs(theta - 98) # shape of prior\nprior = prior / sum(prior) # scales so that prior sums to 1\n\n# data\nn = 208 # sample size\ny = 97.7 # sample mean\nsigma = 1.1 # assumed known\n\n# likelihood\nlikelihood = dnorm(y, theta, sigma / sqrt(n)) # function of theta\n\n# posterior\nproduct = likelihood * prior\nposterior = product / sum(product)\n\nbayes_table = data.frame(theta, prior, likelihood, product, posterior)\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbayes_table |>\n  # scale likelihood for plotting only\n  mutate(likelihood = likelihood / sum(likelihood)) |>\n  select(theta, prior, likelihood, posterior) |>\n  pivot_longer(!theta, names_to = \"source\", values_to = \"probability\") |>\n  mutate(source = fct_relevel(source, \"prior\", \"likelihood\", \"posterior\")) |>\n  ggplot(aes(x = theta, y = probability, col = source)) +\n  geom_line(aes(linetype = source), linewidth = 1) +\n  scale_color_manual(values = bayes_col) +\n  scale_linetype_manual(values = bayes_lty) +\n  theme_bw() +\n  # remove y-axis labels\n  theme(\n    axis.title.y = element_blank(),\n    axis.text.y = element_blank(),\n    axis.ticks.y = element_blank()\n  )\n```\n\n::: {.cell-output-display}\n![](normal-mean_files/figure-pdf/unnamed-chunk-17-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n### Posterior based on sample of size $n=208$ and Normal prior\n\n\nThe only change is the prior\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntheta = seq(96, 100, 0.0001)\n\n# prior\nprior = dnorm(theta, 98.6, 0.3) # shape of prior\nprior = prior / sum(prior) # scales so that prior sums to 1\n\n# data\nn = 208 # sample size\ny = 97.7 # sample mean\nsigma = 1.1 # assumed known\n\n# likelihood\nlikelihood = dnorm(y, theta, sigma / sqrt(n)) # function of theta\n\n# posterior\nproduct = likelihood * prior\nposterior = product / sum(product)\n\nbayes_table = data.frame(theta, prior, likelihood, product, posterior)\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbayes_table |>\n  # scale likelihood for plotting only\n  mutate(likelihood = likelihood / sum(likelihood)) |>\n  select(theta, prior, likelihood, posterior) |>\n  pivot_longer(!theta, names_to = \"source\", values_to = \"probability\") |>\n  mutate(source = fct_relevel(source, \"prior\", \"likelihood\", \"posterior\")) |>\n  ggplot(aes(x = theta, y = probability, col = source)) +\n  geom_line(aes(linetype = source), linewidth = 1) +\n  scale_color_manual(values = bayes_col) +\n  scale_linetype_manual(values = bayes_lty) +\n  theme_bw() +\n  # remove y-axis labels\n  theme(\n    axis.title.y = element_blank(),\n    axis.text.y = element_blank(),\n    axis.ticks.y = element_blank()\n  )\n```\n\n::: {.cell-output-display}\n![](normal-mean_files/figure-pdf/unnamed-chunk-19-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n### Conclusions\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# posterior mean\npost_mean = sum(theta * posterior)\npost_mean\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 97.75464\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# posterior SD\npost_var = sum(theta^2 * posterior) - post_mean^2\n\npost_sd = sqrt(post_var)\npost_sd\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.07391972\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# posterior probability theta is less than 98.6\npnorm(98.6, post_mean, post_sd)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# endpoints of posterior 50% credible interval\nqnorm(c(0.25, 0.75), post_mean, post_sd)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 97.70478 97.80450\n```\n\n\n:::\n\n```{.r .cell-code}\n# endpoints of posterior 80% credible interval\nqnorm(c(0.10, 0.90), post_mean, post_sd)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 97.65991 97.84937\n```\n\n\n:::\n\n```{.r .cell-code}\n# endpoints of posterior 98% credible interval\nqnorm(c(0.01, 0.99), post_mean, post_sd)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 97.58268 97.92660\n```\n\n\n:::\n:::\n\n\n- There is posterior probability pretty close to 100% that population mean healthy human body temperature is less than 98.6 degrees F.\n- There is posterior probability of 50% that population mean healthy human body temperature is between 97.66 and 97.76 degrees F.\nWe believe that the population mean is as likely to be inside this interval as outside.\n- There is posterior probability of 80% that population mean healthy human body temperature is between 97.62 and 97.80 degrees F.\nWe believe that the population mean is 4 times more likely/plausible to be inside this interval than to be outside it.\n- There is posterior probability of 98% that population mean healthy human body temperature is between 97.54 and 97.86 degrees F.\nWe believe that the population mean is 49 times more likely/plausible to be inside this interval than to be outside it.\n\n\n\n\n\n",
    "supporting": [
      "normal-mean_files\\figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}